var oData = {
	categoryItems:["all", "women", "men", "child"],
	sectionItems:["all", "dress", "t-shirt", "onesies", "pants", "sando", "cap"],
	featuredItems:["ls0008","ls0029","ls0017","ls00013","ls0021","ls0030"],
	catalogue:[
		{ "id":"ls0001" , 
		"name":"White Polka dot Dress" ,
		"category":"child" ,
		"section":"dress" ,
		"details":"Now that there is the Tec-9, a crappy spray gun from South Miami. This gun is advertised as the most popular gun in American crime. Do you believe that shit? It actually says that in the little book that comes with it: the most popular gun in American crime. Like they're actually proud of that shit." ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_1.jpg" },

		{ "id":"ls0002" , 
		"name":"Aero Gray Shirt" ,
		"category":"women" ,
		"section":"t-shirt" ,
		"details":"Normally, both your asses would be dead as fucking fried chicken, but you happen to pull this shit while I'm in a transitional period so I don't wanna kill you, I wanna help you. But I can't give you this case, it don't belong to me. Besides, I've already been through too much shit this morning over this case to hand it over to your dumb ass." ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_2.jpg" },

		{ "id":"ls0003" , 
		"name":"Pink Baby Onesies" ,
		"category":"child" ,
		"section":"onesies" ,
		"details":"Look, just because I don't be givin' no man a foot massage don't make it right for Marsellus to throw Antwone into a glass motherfuckin' house, fuckin' up the way the nigger talks. Motherfucker do that shit to me, he better paralyze my ass, 'cause I'll kill the motherfucker, know what I'm sayin'?" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_3.jpg" },

		{ "id":"ls0004" , 
		"name":"Blue Baby Onesies" ,
		"category":"child" ,
		"section":"onesies" ,
		"details":"The path of the righteous man is beset on all sides by the iniquities of the selfish and the tyranny of evil men. Blessed is he who, in the name of charity and good will, shepherds the weak through the valley of darkness, for he is truly his brother's keeper and the finder of lost children. And I will strike down upon thee with great vengeance and furious anger those who would attempt to poison and destroy My brothers. And you will know My name is the Lord when I lay My vengeance upon thee." ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_4.jpg" },

		{ "id":"ls0005" , 
		"name":"White Polka dot Dress" ,
		"category":"child" ,
		"section":"dress" ,
		"details":"My money's in that office, right? If she start giving me some bullshit about it ain't there, and we got to go someplace else and get it, I'm gonna shoot you in the head then and there. Then I'm gonna shoot that bitch in the kneecaps, find out where my goddamn money is. She gonna tell me too. Hey, look at me when I'm talking to you, motherfucker. You listen: we go in there, and that nigga Winston or anybody else is in there, you the first motherfucker to get shot. You understand?" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_5.jpg" },

		{ "id":"ls0006" , 
		"name":"Aeropostale Shirt Pink" ,
		"category":"women" ,
		"section":"T-shirt" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"340.00" ,
		"quantity":"5",
		"image": "images/products/item_6.jpg" },

		{ "id":"ls0007" , 
		"name":"Aero Gray Shirt" ,
		"category":"women" ,
		"section":"t-shirt" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_7.jpg" },

		{ "id":"ls0008" , 
		"name":"Blue Nike Sando" ,
		"category":"men" ,
		"section":"sando" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"220.00" ,
		"quantity":"5",
		"image": "images/products/item_8.jpg" },

		{ "id":"ls0009" , 
		"name":"Green Sports Sando" ,
		"category":"women" ,
		"section":"sando" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_9.jpg" },

		{ "id":"ls0010" , 
		"name":"Blue Aeropostale" ,
		"category":"women" ,
		"section":"T-shirt" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_10.jpg" },

		{ "id":"ls0011" , 
		"name":"Brooklyn Black Shirt" ,
		"category":"men" ,
		"section":"T-shirt" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_11.jpg" },

		{ "id":"ls0012" , 
		"name":"Red Shirt" ,
		"category":"women" ,
		"section":"T-shirt" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_12.jpg" },

		{ "id":"ls0013" , 
		"name":"Red Shirt" ,
		"category":"women" ,
		"section":"T-shirt" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_13.jpg" },

		{ "id":"ls0014" , 
		"name":"Red Shirt" ,
		"category":"women" ,
		"section":"T-shirt" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_14.jpg" },

		{ "id":"ls0015" , 
		"name":"Red Shirt" ,
		"category":"women" ,
		"section":"T-shirt" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_15.jpg" },

		{ "id":"ls0016" , 
		"name":"Red Shirt" ,
		"category":"women" ,
		"section":"T-shirt" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_16.jpg" },

		{ "id":"ls0017" , 
		"name":"Grey Branded Shirt" ,
		"category":"men" ,
		"section":"T-shirt" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_17.jpg" },

		{ "id":"ls0018" , 
		"name":"Red LA CA Shirt" ,
		"category":"men" ,
		"section":"t-shirt" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_18.jpg" },

		{ "id":"ls0019" , 
		"name":"Blue Aeropostale Shirt" ,
		"category":"men" ,
		"section":"t-shirt" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_19.jpg" },

		{ "id":"ls0020" , 
		"name":"Grey Branded Shirt" ,
		"category":"men" ,
		"section":"T-shirt" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_20.jpg" },

		{ "id":"ls0021" , 
		"name":"Light Jansport Bag" ,
		"category":"women" ,
		"section":"bag" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_21.jpg" },

		{ "id":"ls0022" , 
		"name":"Black Printed Jansport" ,
		"category":"women" ,
		"section":"bags" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_22.jpg" },

		{ "id":"ls0023" , 
		"name":"Green Adidas Bag" ,
		"category":"women" ,
		"section":"bag" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"500.00" ,
		"quantity":"5",
		"image": "images/products/item_23.jpg" },

		{ "id":"ls0024" , 
		"name":"Pink Converse Bag" ,
		"category":"women" ,
		"section":"bag" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"400.00" ,
		"quantity":"5",
		"image": "images/products/item_24.jpg" },

		{ "id":"ls0025" , 
		"name":"Yellow Jansport Bag" ,
		"category":"women" ,
		"section":"T-shirt" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_25.jpg" },

		{ "id":"ls0026" , 
		"name":"A Cap" ,
		"category":"men" ,
		"section":"cap" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"300.00" ,
		"quantity":"5",
		"image": "images/products/item_26.jpg" },

		{ "id":"ls0027" , 
		"name":"USA Cap" ,
		"category":"men" ,
		"section":"cap" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"400.00" ,
		"quantity":"5",
		"image": "images/products/item_27.jpg" },

		{ "id":"ls0028" , 
		"name":"New York Cap" ,
		"category":"men" ,
		"section":"cap" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_28.jpg" },

		{ "id":"ls0029" , 
		"name":"Black Pants" ,
		"category":"men" ,
		"section":"pants" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_29.jpg" },

		{ "id":"ls0030" , 
		"name":"Blue Pants" ,
		"category":"men" ,
		"section":"pants" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_30.jpg" },

		{ "id":"ls0031" , 
		"name":"Black Watch" ,
		"category":"men" ,
		"section":"accessories" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_31.jpg" },

		{ "id":"ls0032" , 
		"name":"Green Watch" ,
		"category":"men" ,
		"section":"accessories" ,
		"details":"The quick brown fox jumped over the lazy dogs" ,
		"size":["small", "medium", "large"],
		"price":"200.00" ,
		"quantity":"5",
		"image": "images/products/item_32.jpg" }
		
	]
}

	$( document ).ready(function() {
		/*
	    console.log("-------------------");
	    console.log(oData.catalogue);
	    console.log(oData.catalogue.length);
	    console.log(oData.catalogue[0]);

	    for( var key in oData.catalogue[0]){
	     	console.log(key + " : " + oData.catalogue[0][key]);
	     }
	     */
	});